# 默认hikariDataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.147.128:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #使用第三方druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*.xml  #映射配置文件放在resources下时配置
  type-aliases-package: com.springboot.demo.pojo   # 所有Entity别名类所在包 配置后resultType不用加包名